version: "3.8"

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      NODE_ENV: production
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
