import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Mastiempo from "../../assets/mastiempo.png";
import { FaMagic } from "react-icons/fa";
import { IoMdArrowDropright } from "react-icons/io";
import "./Home.scss";
import Slideemprendedores from "./sliders/Slideemprendedores";
import Slideinfraestructura from "./sliders/Slideinfraestructura";
const Home = () => {
    return (_jsxs("div", { className: "home-landing relative w-full flex justify-center items-center min-h-screen  pt-[68px]", children: [_jsxs("div", { className: "containermiddle-landing mt-[-200px] flex flex-col gap-2 ", children: [_jsxs("div", { className: "Emprendedoresempresarios-landing flex flex-col gap-6", children: [_jsx("h3", { className: " text-[#b9b9b9] font-[600] text-center ", children: "PARA EMPRENDEDORES Y EMPRESARIOS" }), _jsx(Slideemprendedores, {})] }), _jsx("div", { className: "titlemiddle-landing flex justify-center", children: _jsx("img", { src: Mastiempo, className: "mastimepologo w-[1000px] ", alt: "" }) }), _jsxs("div", { className: "bottomiddle-landing flex flex-col gap-4", children: [_jsxs("div", { className: "rowbotonera items-center flex justify-center  gap-5 ", children: [_jsxs("button", { className: "empiezagratis flex gap-2 bg-[#A0DB8E] font-[600] items-center px-[15px] py-[10px] rounded-lg border-[#ccc9c8] border-4 ", children: [_jsx("span", { children: "Empieza gratis" }), _jsx(FaMagic, {})] }), _jsx("button", { className: "descargawindow flex gap-2  font-[600] items-center px-[20px] py-[8px]  text-[#969996] rounded-lg border-[#969996] border-2 ", children: _jsx("span", { children: "Descargar para Windows" }) })] }), _jsx("h4", { className: "descriptionhome-landing text-center text-[#969996] font-[600]  text-[20px] ", children: "Empieza gratis y gestiona tu empresa con procesos automatizados y faciles." })] })] }), _jsxs("div", { className: "bottomcontainer-landing absolute bottom-[50px] gap-[28px] flex flex-col justify-center items-center ", children: [_jsxs("div", { className: "infoslider-landing flex gap-2 text-[#969996] items-center font-[500] ", children: [_jsx(IoMdArrowDropright, {}), _jsx("span", { children: "Infraestructura Segura e Innovadora" })] }), _jsx("div", { className: "sliderinfraestructura-landing ", children: _jsx(Slideinfraestructura, {}) })] })] }));
};
export default Home;
